name: Lint and Format (PR Auto-fix)

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint
      
      # For PRs: Auto-fix formatting
      - name: Auto-fix formatting (PR only)
        if: github.event_name == 'pull_request'
        run: npm run format
      
      - name: Check for changes (PR only)
        if: github.event_name == 'pull_request'
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit formatting changes (PR only)
        if: github.event_name == 'pull_request' && steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "🎨 Auto-fix formatting issues"
          git push
      
      # For direct pushes: Just check formatting
      - name: Check formatting (direct push)
        if: github.event_name == 'push'
        run: npm run format:check